name: CI 7

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install qemu-utils
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd 7
          chmod +x ./build.sh
          ./build.sh
      - name: Release
        run: |
          GIT_TAG=7
          GIT_TAG_HASH=$(git rev-parse --short HEAD)
          GIT_TAG_MESSAGE=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/tags/${GIT_TAG_HASH}" | jq -r '.message' | sed -n '/-----BEGIN PGP SIGNATURE-----/q;p')
          RELEASE_NOTES='!'"[](https://img.shields.io/github/downloads/${GITHUB_REPOSITORY}/${GIT_TAG}/total)"$'\n\n'"${GIT_TAG_MESSAGE}"
          gh release create "${GIT_TAG}" --notes "${RELEASE_NOTES}" --title "CentOS ${GIT_TAG}" ${GIT_TAG}/wsl/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
